# Generated by Django 4.2.3 on 2025-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_users',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reg_users',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
